controller:
  imagePullSecrets:
    - name: regcred
server:
  imagePullSecrets:
    - name: regcred
repoServer:
  imagePullSecrets:
    - name: regcred
applicationSet:
  imagePullSecrets:
    - name: regcred
