apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: petclinic
nodes:
  - role: control-plane
    image: kindest/node:v1.27.3
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 81
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      - containerPort: 6443
        hostPort: 9443
        protocol: TCP
      - containerPort: 30080      # NodePort chosen by ingress-nginx for HTTP
        hostPort: 30080           # Port you’ll hit on the host/LAN
        listenAddress: "0.0.0.0"  # Expose on all interfaces, not just 127.0.0.1
        protocol: TCP
      - containerPort: 30443      # (optional) NodePort for HTTPS
        hostPort: 30443
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
    image: kindest/node:v1.27.3
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "worker=true"
    extraPortMappings:
      - containerPort: 30080      # NodePort chosen by ingress-nginx for HTTP
        hostPort: 30080           # Port you’ll hit on the host/LAN
        listenAddress: "0.0.0.0"