singleBinary:
  replicas: 1

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

loki:
  storage:
    type: "filesystem"
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 10Gi

gateway:
  enabled: true
  service:
    type: ClusterIP
