singleBinary:
  replicas: 0

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

loki:
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  ingester:
    replicas: 1
    securityContext:
      fsGroup: 10001
      runAsUser: 10001
    persistence:
      enabled: false
    extraVolumeMounts:
      - name: loki-storage
        mountPath: /var/loki/chunks
        subPath: chunks
      - name: loki-storage
        mountPath: /var/loki/index
        subPath: index
      - name: loki-storage
        mountPath: /var/loki/cache
        subPath: cache
      - name: loki-storage
        mountPath: /var/loki/rules
        subPath: rules
    extraVolumes:
      - name: loki-storage
        hostPath:
          path: /data/loki/ingester
          type: DirectoryOrCreate

  querier:
    replicas: 1
    securityContext:
      fsGroup: 10001
      runAsUser: 10001
    persistence:
      enabled: false
    extraVolumeMounts:
      - name: loki-storage
        mountPath: /var/loki/chunks
        subPath: chunks
      - name: loki-storage
        mountPath: /var/loki/index
        subPath: index
      - name: loki-storage
        mountPath: /var/loki/cache
        subPath: cache
      - name: loki-storage
        mountPath: /var/loki/rules
        subPath: rules
    extraVolumes:
      - name: loki-storage
        hostPath:
          path: /data/loki/querier
          type: DirectoryOrCreate

  storage_config:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h
    filesystem:
      directory: /var/loki/chunks

gateway:
  enabled: true
  service:
    type: ClusterIP
