singleBinary:
  replicas: 0

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

loki:
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  ingester:
    replicas: 1
    securityContext:
      fsGroup: 10001
      runAsUser: 10001
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "standard" # Use your cluster's storage class
    extraVolumeMounts:
      - name: loki-storage
        mountPath: /var/loki
    extraVolumes:
      - name: loki-storage
        persistentVolumeClaim:
          claimName: loki-ingester-storage

  querier:
    replicas: 1
    securityContext:
      fsGroup: 10001
      runAsUser: 10001
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "standard" # Use your cluster's storage class
    extraVolumeMounts:
      - name: loki-storage
        mountPath: /var/loki
    extraVolumes:
      - name: loki-storage
        persistentVolumeClaim:
          claimName: loki-querier-storage

  storage_config:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h
    filesystem:
      directory: /var/loki/chunks

gateway:
  enabled: true
  service:
    type: ClusterIP
