singleBinary:
  replicas: 0

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

loki:
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  distributor:
    replicas: 1
    securityContext:
      fsGroup: 10001
      runAsUser: 10001

  ingester:
    replicas: 1
    securityContext:
      fsGroup: 10001
      runAsUser: 10001
    persistence:
      enabled: true
      storageClassName: "standard"
      size: 10Gi
    extraVolumeMounts:
      - name: storage
        mountPath: /var/loki
    extraVolumes:
      - name: storage
        persistentVolumeClaim:
          claimName: loki-ingester

  querier:
    replicas: 1
    securityContext:
      fsGroup: 10001
      runAsUser: 10001
    persistence:
      enabled: true
      storageClassName: "standard"
      size: 5Gi
    extraVolumeMounts:
      - name: storage
        mountPath: /var/loki
    extraVolumes:
      - name: storage
        persistentVolumeClaim:
          claimName: loki-querier

  schema_config:
    configs:
      - from: 2025-06-07
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage:
    type: "filesystem"
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin

  storage_config:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h
    filesystem:
      directory: /var/loki/chunks

gateway:
  enabled: true
  service:
    type: ClusterIP
