singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path-immediate

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

nameOverride: ""
fullnameOverride: ""
namespace: logging

loki:
  useTestSchema: true
  auth_enabled: false
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  storage:
    type: filesystem

  storage_config:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h
    filesystem:
      directory: /var/loki/chunks

  schema_config:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v12
        index:
          prefix: loki_index_
          period: 24h

gateway:
  enabled: true
  service:
    type: ClusterIP
