singleBinary:
  replicas: 0

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

nameOverride: ""
fullnameOverride: ""
namespace: logging

loki:
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

  ingester:
    replicas: 1
    securityContext:
      fsGroup: 10001
      runAsUser: 10001
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "standard"
      existingClaim: loki-ingester-storage
    extraVolumeMounts:
      - name: loki-storage
        mountPath: /var/loki/ingester
    extraVolumes:
      - name: loki-storage
        persistentVolumeClaim:
          claimName: loki-ingester-storage

  querier:
    replicas: 1
    securityContext:
      fsGroup: 10001
      runAsUser: 10001
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "standard"
      existingClaim: loki-querier-storage
    extraVolumeMounts:
      - name: loki-storage
        mountPath: /var/loki/querier
    extraVolumes:
      - name: loki-storage
        persistentVolumeClaim:
          claimName: loki-querier-storage

  storage_config:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/ingester/index
      cache_location: /var/loki/ingester/cache
      cache_ttl: 24h
    filesystem:
      directory: /var/loki/ingester/chunks

gateway:
  enabled: true
  service:
    type: ClusterIP
