deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: false

  extraVolumeMounts:
    - name: loki-storage
      mountPath: /var/loki

  extraVolumes:
    - name: loki-storage
      persistentVolumeClaim:
        claimName: loki-storage

nameOverride: ""
fullnameOverride: ""
namespace: logging

loki:
  useTestSchema: true
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  storage:
    type: filesystem

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h
    filesystem:
      directory: /var/loki/chunks

  schema_config:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v12
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true

# gateway:
#   enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
