singleBinary:
  replicas: 0

write:
  replicas: 1

read:
  replicas: 1

backend:
  replicas: 1

nameOverride: ""
fullnameOverride: ""
namespace: logging

loki:
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  storage:
    type: filesystem

  ingester:
    replicas: 1
    persistence:
      enabled: true
      existingClaim: loki-ingester-storage
    extraVolumeMounts:
      - name: storage
        mountPath: /var/loki
    extraVolumes:
      - name: storage
        persistentVolumeClaim:
          claimName: loki-ingester-storage

  querier:
    replicas: 1
    persistence:
      enabled: true
      existingClaim: loki-querier-storage
    extraVolumeMounts:
      - name: storage
        mountPath: /var/loki
    extraVolumes:
      - name: storage
        persistentVolumeClaim:
          claimName: loki-querier-storage

  storage_config:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h
    filesystem:
      directory: /var/loki/chunks

gateway:
  enabled: true
  service:
    type: ClusterIP
