apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
spec:
  storageClassName: local-path-immediate
  capacity:
    storage: 10Gi  
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/storage/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - petclinic-worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path-immediate
  
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: loki-ingester-pv
# spec:
#   storageClassName: local-path-immediate
#   capacity:
#     storage: 10Gi  
#   accessModes:
#     - ReadWriteOnce
#   local:
#     path: /mnt/storage/loki-ingester  
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - petclinic-worker 
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: loki-querier-pv
# spec:
#   storageClassName: local-path-immediate
#   capacity:
#     storage: 10Gi  
#   accessModes:
#     - ReadWriteOnce
#   local:
#     path: /mnt/storage/loki-querier
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - petclinic-worker
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: loki-ingester-storage
#   namespace: logging
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: local-path-immediate
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: loki-querier-storage
#   namespace: logging
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: local-path-immediate
