singleBinary:
  replicas: 1

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

loki:
  schemaConfig:
    configs:
      - from: 2025-06-08
        store: standard
        object_store: filesystem
        schema: v16
        index:
          prefix: index_
          period: 24h
  storage:
    type: "filesystem"
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 10Gi

gateway:
  enabled: true
  service:
    type: ClusterIP
