singleBinary:
  replicas: 1

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

loki:
  distributor:
    securityContext:
      fsGroup: 10001
      runAsUser: 10001

  ingester:
    securityContext:
      fsGroup: 10001
      runAsUser: 10001

  querier:
    securityContext:
      fsGroup: 10001
      runAsUser: 10001
  schemaConfig:
    configs:
      - from: 2025-06-07
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  storage:
    type: "filesystem"
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 10Gi

gateway:
  enabled: true
  service:
    type: ClusterIP
