apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-immediate
provisioner: rancher.io/local-path
volumeBindingMode: Immediate  # Allow immediate PVC binding
parameters:
  nodePath: /mnt/storage  
reclaimPolicy: Delete
