prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
    maximumStartupDurationSeconds: 60

kubeEtcd:
  enabled: false
kubeScheduler:
  serviceMonitor:
    enabled: false
kubeProxy:
  serviceMonitor:
    enabled: false