apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  namespace: dev
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: spring-pet-clinic
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - dev