apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      metrics: "true"
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
