configmap:
  enabled: true

config:
  clients:
    - url: http://loki-loki-distributed-gateway:80/loki/api/v1/push

  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names: ["dev", "default"]

      relabel_configs:
        # Only specific services
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: (visits-service|customers-service|vets-service|api-gateway|config-server|discovery-server)
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
          target_label: __path__

      pipeline_stages:
        - cri: {}

resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 100m

# Increase file descriptor limits
securityContext:
  runAsUser: 0
  runAsGroup: 0

# Set environment variables to increase limits
env:
  - name: GOGC
    value: "10"

tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
