apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true

  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - discovery-server
          - customers-service
          - visits-service
          - vets-service
          - genai-service
          - api-gateway
          - admin-server

  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
