apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true

  selector:
    matchLabels:
      metrics: "true"

  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
