apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-spring-servicemonitor
  namespace: dev-21
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      metrics: "true"
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - dev-21