resources:
  requests:
    memory: "256Mi"
    cpu: "50m"
  limits:
    memory: "512Mi"
    cpu: "200m"

env:
  - name: JAVA_TOOL_OPTIONS  
    value: >
      -Xms128m -Xmx350m
      -XX:MaxRAMPercentage=70
      -XX:+UseSerialGC
      -XX:+ExitOnOutOfMemoryError
  - name: MEM_MAX_SPANS
    value: "30000"   