namespace: staging
replicaCount: 1

images:
  config-server:
    image: mikenam/spring-petclinic-config-server
    tag: v1.1.10
    
  customers-service:
    image: mikenam/spring-petclinic-customers-service
    tag: v1.1.10

  discovery-server:
    image: mikenam/spring-petclinic-discovery-server
    tag: v1.1.10

  visits-service:
    image: mikenam/spring-petclinic-visits-service
    tag: v1.1.10

  vets-service:
    image: mikenam/spring-petclinic-vets-service
    tag: v1.1.10

  genai-service:
    image: mikenam/spring-petclinic-genai-service
    tag: v1.1.10

  api-gateway:
    image: mikenam/spring-petclinic-api-gateway
    tag: v1.1.10

  admin-server:
    image: mikenam/spring-petclinic-admin-server
    tag: v1.1.10

services:
  config-server:
    containerName: config-server
    port: 8888
    metrics: "false"
    
  customers-service:
    containerName: customers-service
    port: 8081
    dependOnConfigServer: true
    metrics: "true"

  discovery-server:
    containerName: discovery-server
    port: 8761
    dependOnConfigServer: true
    metrics: "true"

  visits-service:
    containerName: visits-service
    port: 8082
    dependOnConfigServer: true
    metrics: "true"

  vets-service:
    containerName: vets-service
    port: 8083
    dependOnConfigServer: true
    metrics: "true"

  api-gateway:
    containerName: api-gateway
    port: 8080
    dependOnConfigServer: true
    metrics: "true"

  admin-server:
    containerName: admin-server
    port: 9090
    dependOnConfigServer: true
    metrics: "true"
