apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-${NAMESPACE}-servicemonitor
  namespace: ${NAMESPACE}
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ${NAMESPACE}

  selector:
    matchLabels:
      metrics: "true"

  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
