grafana:
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-operated.monitoring.svc:9090
      isDefault: true
      jsonData:
        exemplarTraceIdDestinations:
          - name: trace_id
            datasourceUid: zipkin
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
  extraConfigmapMounts:
    - name: grafana-datasources
      mountPath: /etc/grafana/provisioning/datasources
      configMap: grafana-datasources
      readOnly: true
  persistence:
    enabled: true
    size: 500Mi