prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
    maximumStartupDurationSeconds: 60
    enableFeatures:
      - exemplar-storage

kubeEtcd:
  enabled: false
kubeScheduler:
  serviceMonitor:
    enabled: false
kubeProxy:
  serviceMonitor:
    enabled: false

rule_files:
  - ./rules.yaml