prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    maximumStartupDurationSeconds: 60
    enableFeatures:
      - exemplar-storage
  persistence:
    enabled: true
    size: 500Mi
    
grafana:
  init-chown-data: false
  persistence:
    enabled: true
    size: 500Mi