prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    maximumStartupDurationSeconds: 60
    enableFeatures:
      - exemplar-storage
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 8Gi

    
grafana:
  init-chown-data: false
  persistence:
    enabled: true
    size: 500Mi