prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    enableFeatures:
      - exemplar-storage
  persistence:
    enabled: true
    size: 500Mi
    
grafana:
  persistence:
    enabled: true
    size: 500Mi