groups:
  - name: petclinic-5xx
    rules:
      - alert: High5xxErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[30s]) * 15 > 10
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.application }} 5xx rate is high"
          description: |
            {{ $labels.instance }} ({{ $labels.application }}) is returning
            >1 5xx responses per second for 2 minutes.
