apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devops-rules
  labels:
    release: prometheus
spec:
  groups:
    - name: petclinic-5xx
      rules:
        - alert: High5xxErrorRate
          expr: increase(http_server_requests_seconds_count{status=~"5.."}[30s]) > 10
          labels:
            application: petclinic
            severity: critical
          annotations:
            summary: "{{ $labels.service }} in namespace {{ $labels.namespace }} 5xx rate is high"
            description: |
              {{ $labels. }} ({{ $labels.service }} namespace {{ $labels.namespace }}) is returning more than 10 5xx errors in the last 30 seconds.
