apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-rules
  labels:
    release: prometheus
spec:
  groups:
    - name: petclinic-5xx
      rules:
        - alert: High5xxErrorRate
          expr: increase(http_server_requests_seconds_count{status=~"5.."}[30s]) > 10
          labels:
            severity: critical
          annotations:
            summary: "{{ $labels.application }} 5xx rate is high"
            description: |
              {{ $labels.instance }} ({{ $labels.application }}) is returning more than 10 5xx errors in the last 30 seconds.
