namespace: dev
replicaCount: 1
imagePullPolicy: IfNotPresent

images:
  config-server:
    image: mikenam/spring-petclinic-config-server
    tag: 1f62b7e
    
  customers-service:
    image: mikenam/spring-petclinic-customers-service
    tag: 5416bad

  discovery-server:
    image: mikenam/spring-petclinic-discovery-server
    tag: 1f62b7e

  visits-service:
    image: mikenam/spring-petclinic-visits-service
    tag: 1f62b7e

  vets-service:
    image: mikenam/spring-petclinic-vets-service
    tag: b1de945

  genai-service:
    image: mikenam/spring-petclinic-genai-service
    tag: 1f62b7e

  api-gateway:
    image: mikenam/spring-petclinic-api-gateway
    tag: 1f62b7e

  admin-server:
    image: mikenam/spring-petclinic-admin-server
    tag: 1f62b7e

services:
  config-server:
    containerName: config-server
    port: 8888
    metrics: "false"
    
  customers-service:
    containerName: customers-service
    port: 8081
    dependOnConfigServer: true
    metrics: "true"

  discovery-server:
    containerName: discovery-server
    port: 8761
    dependOnConfigServer: true
    metrics: "true"

  visits-service:
    containerName: visits-service
    port: 8082
    dependOnConfigServer: true
    metrics: "true"

  vets-service:
    containerName: vets-service
    port: 8083
    dependOnConfigServer: true
    metrics: "true"

  api-gateway:
    containerName: api-gateway
    port: 8080
    dependOnConfigServer: true
    metrics: "true"

  admin-server:
    containerName: admin-server
    port: 9090
    dependOnConfigServer: true
    metrics: "true"
