{{- range $name, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.containerName }}
  labels:
    app.kubernetes.io/name: {{ $config.containerName }}
    metrics: {{ if $config.metrics }}"true"{{ else }}"false"{{ end }}
spec:
  selector:
    app: {{ $config.containerName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
{{- end }}