{{- range $name, $config := .Values.services }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $config.containerName }}-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ $config.containerName }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
