apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-staging-servicemonitor
  namespace: staging
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - staging

  selector:
    matchLabels:
      metrics: "true"

  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
